### ISSUE TITLE
How can I solve this? Any suggestion?

### ISSUE THREAD

**Issue by sarwarcse** [InternetExplorer/modern.IE-static-code-scan#85]
To scan a private url go to http://localhost:1337/ and follow the instructions
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (E:\mordern\modern.IE-static-code-scan-master\node_modules\
request\request.js:583:30)
    at Request.end (E:\mordern\modern.IE-static-code-scan-master\node_modules\re
quest\request.js:1237:28)
    at E:\mordern\modern.IE-static-code-scan-master\node_modules\request\request
.js:413:12
    at process._tickCallback (node.js:355:11)

**Comment by molant** [comment]
There is already an issue reporting this and the workaround at the moment is to downgrade to 0.10.36. The scanner doesn't work at the moment with node 0.12

-----Original Message-----

**Comment by molant** [comment]
See #83

**Comment by sarwarcse** [comment]
Thanks Molant.. it solved..
